# -*- coding: utf-8 -*-
"""credit card.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Ui8g8Ro0d9lXt587qPPI0R7C7ybSmKd
"""

# =====================================================================
# SECTION 1: CLEAN ENVIRONMENT SETUP & DATA LOADING
# =====================================================================

# 1. Core Data Manipulation & Math Libraries
import numpy as np  # For fast matrix and numerical operations
import pandas as pd  # For handling structured DataFrames

# 2. Data Visualization Libraries
import matplotlib.pyplot as plt  # Core plotting engine
import missingno as msno  # To visualize missing data patterns
import plotly.express as px  # For interactive, dynamic charts
import seaborn as sns  # Advanced statistical plots

# 3. Machine Learning Models & Metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from sklearn.metrics import hamming_loss, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("📦 Core data science and ML libraries loaded successfully!")

# =====================================================================
# DATA LOADING FROM LOCAL HARD DRIVE
# =====================================================================

# =====================================================================
# ONLY DATASET UPLOADING & LOADING PART
# =====================================================================
import os
import zipfile
import pandas as pd

# STEP 1: Define the path to your uploaded zip file.
# Since you used the "Copy path" option in Colab, paste it exactly here.
zip_path = "/archive.zip"

# STEP 2: Extract the contents of the zip file into Colab
print("🔄 Unzipping your file... please wait...")
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("/content/")
print("🔓 Unzipping complete!")

# STEP 3: Automatically find the newly extracted CSV file name
# This looks inside your folder and catches the CSV file automatically so you don't have to guess its name.
extracted_files = os.listdir("/content/")
csv_file = [file for file in extracted_files if file.endswith(".csv")][0]
print(f"📄 Found extracted CSV file: {csv_file}")

# STEP 4: Load the CSV file into a Pandas DataFrame called 'data'
print("⏳ Loading CSV data into memory...")
data = pd.read_csv(f"/content/{csv_file}")

print("\n🚀 SUCCESS! Your dataset is fully loaded and ready to use.")
print(f"Dataset Shape: {data.shape[0]} rows, {data.shape[1]} columns")

data



data.info()
print("-----------------SHAPE-----------------")
data.shape

msno.bar(data)

duplicate_count = len(data[data.duplicated()])
duplicate_count

new_column_names = {
    'nameOrig': 'origin',
    'oldbalanceOrg': 'sender_old_bal',
    'newbalanceOrig': 'sender_new_bal',
    'nameDest': 'dest',
    'oldbalanceDest': 'dest_old_bal',
    'newbalanceDest': 'dest_new_bal'
}

data.rename(columns=new_column_names, inplace=True)

data

columns_to_drop = ['step', 'isFlaggedFraud']
data.drop(columns=columns_to_drop, inplace=True)

data

def plot_fraud_by_transaction_type(data):
    plt.figure(figsize=(15, 8))
    g = sns.countplot(data=data, x='type', hue='isFraud', palette='dark', alpha=0.6)
    plt.title("Checking for fraud occurrences for each Transaction types")

    # Finding counts and annotating
    annotate_counts(g)

def annotate_counts(ax):
    for p in ax.patches:
        ax.annotate(p.get_height(), (p.get_x() + 0.04, p.get_height() + 10000))

plot_fraud_by_transaction_type(data)
plt.show()

transfer_fraud = data[(data['type'] == 'TRANSFER') & (data['isFraud'] == 1)]
transfer_fraud_counts = data[(data['type'] == 'TRANSFER') & (data['isFraud'] == 1)]['origin'].value_counts()

transfer_fraud_counts

cashOut_fraud = data[(data['type']=='CASH_OUT') & (data['isFraud']==1)]
cashOut_fraud_count = data[(data['type']=='CASH_OUT') & (data['isFraud']==1)]['origin'].value_counts()

cashOut_fraud_count

transfer_fraud['dest'].value_counts()

cashOut_fraud['dest'].value_counts()

is_dest_in_cashout_origin = transfer_fraud['dest'].isin(cashOut_fraud['origin']).any()
trans_cashout = data[data['type'] == 'TRANSFER']
is_dest_in_trans_cashout_origin = transfer_fraud['dest'].isin(trans_cashout['origin']).any()
count_dest_in_trans_cashout_origin = transfer_fraud['dest'].isin(trans_cashout['origin']).sum()
print(f"Is destination in cashOut origin? {is_dest_in_cashout_origin}")
print(f"Is destination in trans_cashout origin? {is_dest_in_trans_cashout_origin}")
print(f"Count of destinations in trans_cashout origin: {transfer_fraud.dest.isin(trans_cashout.origin).count()}")

"""Feature Engineering
Creating new column client_type having 4 categories and dropping 'origin' and 'dest'
CC - Customer to Customer
CM - Customer to Merchant
MC - Merchant to Customer
MM - Merchant to Merchant
"""

print(data.columns)

# 1. Filter the dataset to keep ONLY TRANSFER and CASH_OUT transactions
cleaned_df = data[data["type"].isin(["TRANSFER", "CASH_OUT"])].copy()

# 2. Calculate balance error for origin (sender) account
# In a perfect transaction: old_balance - amount = new_balance.
cleaned_df["errorBalanceOrig"] = (
    cleaned_df["sender_new_bal"]
    + cleaned_df["amount"]
    - cleaned_df["sender_old_bal"]
)

# 3. Calculate balance error for destination (receiver) account
# In a perfect transaction: old_balance + amount = new_balance.
cleaned_df["errorBalanceDest"] = (
    cleaned_df["dest_old_bal"] + cleaned_df["amount"] - cleaned_df["dest_new_bal"]
)

# 4. One-hot encode the 'type' column (converts TRANSFER/CASH_OUT into 1 and 0)
cleaned_df = pd.get_dummies(cleaned_df, columns=["type"], drop_first=True)

print("Cell 2 Success! Cleaned and engineered features successfully.")
print(f"Final dataset shape ready for ML: {cleaned_df.shape}")
cleaned_df.head(3)

# =====================================================================
# DATA VISUALIZATION SECTION
# =====================================================================
import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure canvas for two distinct plots side-by-side
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: Boxplot of Transaction Amounts (Fraud vs. Legitimate)
# This shows us if fraud cases involve significantly larger sums of money
sns.boxplot(
    ax=axes[0],
    x="isFraud",
    y="amount",
    data=cleaned_df,
    palette=["#2ecc71", "#e74c3c"],
)
axes[0].set_title("Distribution of Transaction Amounts")
axes[0].set_xlabel("Is Fraud? (0 = No, 1 = Yes)")
axes[0].set_ylabel("Amount (in Millions)")
axes[0].set_yscale("log")  # Using log scale to handle extreme outliers easily

# Plot 2: Scatter Plot of Error Balance vs. Transaction Amount
# This visualizes how our custom engineered feature instantly separates fraud from clean data
sns.scatterplot(
    ax=axes[1],
    x="amount",
    y="errorBalanceOrig",
    hue="isFraud",
    data=cleaned_df.sample(
        100000, random_state=42
    ),  # Sampling 100k points so Colab doesn't freeze
    palette=["#2ecc71", "#e74c3c"],
    alpha=0.6,
)
axes[1].set_title("Amount vs Sender Balance Error (100k Sample Points)")
axes[1].set_xlabel("Transaction Amount")
axes[1].set_ylabel("Sender Balance Error")

plt.tight_layout()
plt.show()

# =====================================================================
# SECTION 5: SPLITTING THE DATA
# =====================================================================

# 1. Separate our features (X) from our target label (y)
# 'isFraud' is what we want to predict, so it goes to y. Everything else goes to X.
X = cleaned_df.drop(columns=["isFraud"])
y = cleaned_df["isFraud"]

# 2. Split the data into 80% Training and 20% Testing
# We use 'stratify=y' because fraud is highly imbalanced. This ensures both the train
# and test sets get the exact same percentage of fraud cases.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

print("Cell 5 Success! Data split completed safely.")
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape: {X_test.shape}")
print(f"Fraud cases in Training Set: {sum(y_train)}")
print(f"Fraud cases in Testing Set: {sum(y_test)}")

# =====================================================================
# SECTION 6: FEATURE SCALING
# =====================================================================

# 1. Initialize the StandardScaler
scaler = StandardScaler()

# 2. Fit and transform the training data
# 'Fit' calculates the mean and variance of X_train.
# 'Transform' applies the mathematical formula to scale the data.
X_train_scaled = scaler.fit_transform(X_train)

# 3. Transform the testing data
# CRITICAL: We ONLY transform X_test. We do NOT fit it.
X_test_scaled = scaler.transform(X_test)

print("Cell 6 Success! Feature scaling applied perfectly.")
print(f"Scaled Training sample (First row):\n{X_train_scaled[0]}")

# =====================================================================
# SECTION 7: LOGISTIC REGRESSION BASELINE
# =====================================================================

# 1. Initialize the model
# We use class_weight='balanced' to handle the heavy class imbalance automatically
log_reg = LogisticRegression(class_weight="balanced", random_state=42, max_iter=500)

# 2. Train the model on our scaled training data
print("⏳ Training Logistic Regression Baseline model... please wait...")
log_reg.fit(X_train_scaled, y_train)
print("🎯 Model training complete!")

# 3. Make predictions on the scaled testing data
y_pred = log_reg.predict(X_test_scaled)
y_pred_proba = log_reg.predict_proba(X_test_scaled)[
    :, 1
]  # Probabilities needed for ROC-AUC

# 4. Evaluate using our specific fraud metrics
auc_score = roc_auc_score(y_test, y_pred_proba)
h_loss = hamming_loss(y_test, y_pred)

print("\n--- BASELINE EVALUATION METRICS ---")
print(f"ROC-AUC Score: {auc_score:.4f}")
print(f"Hamming Loss:  {h_loss:.6f}")

# =====================================================================
# SECTION 7.1: DETAILED CONFUSION MATRIX & CLASSIFICATION REPORT
# =====================================================================
from sklearn.metrics import classification_report, confusion_matrix

# 1. Generate the Confusion Matrix
# This counts True Negatives, False Positives, False Negatives, and True Positives
cm = confusion_matrix(y_test, y_pred)

print("--- CONFUSION MATRIX BREAKDOWN ---")
print(f"True Legitimate Caught (True Negatives):   {cm[0][0]}")
print(f"False Alarms Raised (False Positives):     {cm[0][1]}")
print(f"Missed Fraud Cases (False Negatives):      {cm[1][0]}")
print(f"True Fraud Caught (True Positives):        {cm[1][1]}")

# 2. Print the Precision, Recall, and F1-Score
print("\n--- DETAILED CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred, target_names=["Legit", "Fraud"]))

# =====================================================================
# SECTION 8: RANDOM FOREST MODEL
# =====================================================================
from sklearn.ensemble import RandomForestClassifier

# 1. Initialize the Random Forest
# We use n_estimators=50 to train faster in Colab, and class_weight='balanced' for the imbalance.
rf_model = RandomForestClassifier(
    n_estimators=50, class_weight="balanced", random_state=42, n_jobs=-1
)

print("⏳ Training Random Forest (50 Trees)... This might take 1-2 minutes...")
rf_model.fit(X_train_scaled, y_train)
print("🎯 Random Forest training complete!")

# 2. Make predictions
y_pred_rf = rf_model.predict(X_test_scaled)
y_pred_proba_rf = rf_model.predict_proba(X_test_scaled)[:, 1]

# 3. Print the new Confusion Matrix and Classification Report
print("\n--- RANDOM FOREST CONFUSION MATRIX ---")
print(confusion_matrix(y_test, y_pred_rf))

print("\n--- RANDOM FOREST CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred_rf, target_names=["Legit", "Fraud"]))

# =====================================================================
# SECTION 9: XGBOOST CLASSIFIER
# =====================================================================
from xgboost import XGBClassifier

# Calculate scale_pos_weight to help XGBoost handle the class imbalance
# Formula: total_negative_examples / total_positive_examples
neg_count = len(y_train) - sum(y_train)
pos_count = sum(y_train)
scale_weight = neg_count / pos_count

# 1. Initialize XGBoost with optimized production settings
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=scale_weight,
    random_state=42,
    tree_method="hist",  # Speeds up training significantly on large datasets
)

print("⏳ Training XGBoost Model... please wait...")
xgb_model.fit(X_train_scaled, y_train)
print("🎯 XGBoost training complete!")

# 2. Make predictions
y_pred_xgb = xgb_model.predict(X_test_scaled)

# 3. Print evaluation matrix
print("\n--- XGBOOST CONFUSION MATRIX ---")
print(confusion_matrix(y_test, y_pred_xgb))

print("\n--- XGBOOST CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred_xgb, target_names=["Legit", "Fraud"]))

# =====================================================================
# SECTION 10: TENSORFLOW DEEP LEARNING NEURAL NETWORK
# =====================================================================
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Sequential

# 1. Calculate class weights for TensorFlow to balance the loss function
# Total samples / (2 * class_samples)
total_samples = len(y_train)
weight_for_0 = total_samples / (2.0 * (total_samples - sum(y_train)))
weight_for_1 = total_samples / (2.0 * sum(y_train))
class_weights = {0: weight_for_0, 1: weight_for_1}

# 2. Build the Multi-Layer Perceptron Architecture
nn_model = Sequential(
    [
        # Input Layer + First Hidden Layer (8 features in -> 32 neurons)
        Dense(32, activation="relu", input_shape=(X_train_scaled.shape[1],)),
        Dropout(0.2),  # Randomly deactivates 20% of neurons to stop overfitting
        # Second Hidden Layer
        Dense(16, activation="relu"),
        Dropout(0.2),
        # Output Layer: Single neuron with Sigmoid outputs a probability between 0 and 1
        Dense(1, activation="sigmoid"),
    ]
)

# 3. Compile the model with Adam optimizer and Binary Crossentropy loss
nn_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy", tf.keras.metrics.Recall()],
)

print("⏳ Training the Neural Network (3 Epochs)... please wait...")
# 4. Train the network
history = nn_model.fit(
    X_train_scaled,
    y_train,
    epochs=3,
    batch_size=2048,  # Large batch size helps process 2.2 million rows quickly
    class_weight=class_weights,
    validation_split=0.1,
    verbose=1,
)
print("🎯 Neural Network training complete!")

# =====================================================================
# SECTION 10.1: NEURAL NETWORK EVALUATION
# =====================================================================

# 1. Generate probability predictions on the scaled test set
y_pred_proba_nn = nn_model.predict(X_test_scaled)

# 2. Convert probabilities to binary outcomes (0 or 1) using a 0.5 threshold
y_pred_nn = (y_pred_proba_nn >= 0.5).astype(int).flatten()

# 3. Print the Confusion Matrix and Classification Report
print("--- NEURAL NETWORK CONFUSION MATRIX ---")
print(confusion_matrix(y_test, y_pred_nn))

print("\n--- NEURAL NETWORK CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred_nn, target_names=["Legit", "Fraud"]))

# =====================================================================
# SECTION 11: FINAL MODEL COMPARISON METRICS (FIXED IMPORTS)
# =====================================================================
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# 1. Gather metrics for all trained models
model_metrics = {
    "Model Name": [
        "Logistic Regression (Baseline)",
        "Random Forest",
        "XGBoost Classifier",
        "Neural Network (Keras)",
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xgb),
        accuracy_score(y_test, y_pred_nn),
    ],
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_xgb),
        precision_score(y_test, y_pred_nn),
    ],
    "Recall (Sensitivity)": [
        recall_score(y_test, y_pred),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_xgb),
        recall_score(y_test, y_pred_nn),
    ],
    "F1-Score": [
        f1_score(y_test, y_pred),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_xgb),
        f1_score(y_test, y_pred_nn),
    ],
}

# 2. Convert to a DataFrame and display beautifully
comparison_df = pd.DataFrame(model_metrics)
print("--- END-TO-END MODEL PERFORMANCE EVALUATION ---")
comparison_df.round(4)

# =====================================================================
# GRAPHICAL VISUALIZATION DASHBOARD
# =====================================================================
import matplotlib.pyplot as plt
import seaborn as sns

# Set a clean, professional aesthetic
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# ---------------------------------------------------------------------
# PLOT 1: F1-Score Model Comparison Bar Chart
# ---------------------------------------------------------------------
# Sorting data for better visual flow
sorted_df = comparison_df.sort_values(by="F1-Score", ascending=False)

barplot = sns.barplot(
    ax=axes[0],
    x="F1-Score",
    y="Model Name",
    data=sorted_df,
    palette="viridis",
    hue="Model Name",
    legend=False,
)

# Add value labels to the end of each bar
for index, value in enumerate(sorted_df["F1-Score"]):
    axes[0].text(
        value - 0.08 if value > 0.1 else value + 0.01,
        index,
        f"{value:.4f}",
        va="center",
        ha="right" if value > 0.1 else "left",
        color="white" if value > 0.1 else "black",
        fontweight="bold",
    )

axes[0].set_title(
    "Model Performance Comparison (F1-Score)", fontsize=14, fontweight="bold"
)
axes[0].set_xlabel("F1-Score (Higher is Better)", fontsize=12)
axes[0].set_ylabel("")
axes[0].set_xlim(0, 1.1)

# ---------------------------------------------------------------------
# PLOT 2: Random Forest Confusion Matrix Heatmap
# ---------------------------------------------------------------------
# Re-generating the winning model's matrix array
rf_cm = confusion_matrix(y_test, y_pred_rf)

# Dynamic labels with text description for clarity
labels = [
    [f"True Legit\n{rf_cm[0][0]}", f"False Alarm\n{rf_cm[0][1]}"],
    [f"Missed Fraud\n{rf_cm[1][0]}", f"Caught Fraud\n{rf_cm[1][1]}"],
]

sns.heatmap(
    rf_cm,
    ax=axes[1],
    annot=labels,
    fmt="",
    cmap="Blues",
    cbar=False,
    annot_kws={"size": 14, "fontweight": "bold"},
    xticklabels=["Predicted Legit", "Predicted Fraud"],
    yticklabels=["Actual Legit", "Actual Fraud"],
)

axes[1].set_title(
    "Winning Random Forest Confusion Matrix", fontsize=14, fontweight="bold"
)
axes[1].tick_params(axis="both", which="major", labelsize=11)

# Final clean adjustments
plt.suptitle(
    "Credit Card Fraud Detection Pipeline - Performance Metrics",
    fontsize=18,
    fontweight="bold",
    y=1.02,
)
plt.tight_layout()
plt.show()

# =====================================================================
# FEATURE IMPORTANCE VISUALIZATION
# =====================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Extract feature importances from the trained Random Forest
importances = rf_model.feature_importances_
feature_names = X_train.columns

# 2. Create a DataFrame sorted by importance
feat_imp_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance Score": importances
}).sort_values(by="Importance Score", ascending=False)

# 3. Plot the data
plt.figure(figsize=(12, 6))
sns.set_theme(style="whitegrid")

# Create a horizontal bar plot for maximum scannability
sns.barplot(
    x="Importance Score",
    y="Feature",
    data=feat_imp_df,
    palette="plasma",
    hue="Feature",
    legend=False
)

# Customize fonts and layout to match the dashboard aesthetic
plt.title("What Variables Drive Fraud Detection? (Feature Importance)", fontsize=15, fontweight="bold", pad=15)
plt.xlabel("Relative Importance Score", fontsize=12)
plt.ylabel("")
plt.tight_layout()
plt.show()

# =====================================================================
# SECTION 12: SAVING THE MODEL & SCALER FOR PRODUCTION
# =====================================================================
import pickle

# 1. Save the trained Random Forest model to a file
model_filename = "winning_random_forest_model.pkl"
with open(model_filename, "wb") as model_file:
    pickle.dump(rf_model, model_file)

# 2. Save the StandardScaler (CRITICAL: You must use the exact same scaler for new data!)
scaler_filename = "production_scaler.pkl"
with open(scaler_filename, "wb") as scaler_file:
    pickle.dump(scaler, scaler_file)

print("--- PIPELINE ARTIFACTS SAVED SUCCESSFULLY ---")
print(f"1. Saved Model File:  {model_filename}")
print(f"2. Saved Scaler File: {scaler_filename}")
print(
    "\n💡 Success: Refresh your Google Colab left sidebar file explorer. You will see both files there ready to download!"
)

from google.colab import files

# Force download the model
print("Downloading model...")
files.download("winning_random_forest_model.pkl")

# Force download the scaler
print("Downloading scaler...")
files.download("production_scaler.pkl")